sudo: required
dist: trusty

language: node_js
node_js:
  - '7.7.4'

branches:
  only:
    - master

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

before_install:
  - sudo apt-get update -q
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb

before_script:
- npm install @angular/cli
- npm install -g karma
- npm install

script:
  - cd cityCommunicationApp
  - ng build --prod
